### ISSUE TITLE
Bulk Copy

### ISSUE THREAD

**Issue by TomAugspurger** [mapd/pymapd#9]
https://www.mapd.com/docs/latest/mapd-core-guide/loading-data/

We can currently `.execute(COPY <table> from <file>)`, but the `<file>` is relative to the mapd server.

Look into `client.import_table` and `client.insert_data`.

**Comment by andrewseidl** [comment]
To clarify, `insert_data` is currently an internal-only interface.

`load_table` and `load_table_binary` are currently your best options for loading in data without having to dump to a server-side file. Downside of those calls are that they currently require the input data to be row-ordered instead of columnar. Some sample code is at https://github.com/mapd/mapd-core/blob/master/SampleCode/stream_insert.py . The difference between the two calls are that `load_table` requires each field to be a string which will then be parsed on the server; `load_table_binary` requires them to be the correct type for the column.

@tmostak and I discussed this a bit last night, we're planning on adding support for columnar input soon, but we don't have a timeline for it yet.

**Comment by billmaimone** [comment]
@TomAugspurger If we don't have columnar input, is the net impact to time, space, or both?  If we gave you columns instead of rows what do we save?
